name: dataworks-etl
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dataworks_etl_rails
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
