name: dataworks-etl
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dataworks_etl_rails
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  solr:
    image: solr:9.6.1
    command: solr-create -c dataworks
    ports:
      - 8983:8983

volumes:
  postgres-data:
