$id: "https://dataworks.stanford.edu/dataworks-0.0.1.yml"
title: Dataworks Schema
description: >
  A schema for validating dataset metadata for the Dataworks application.

  Unless otherwise specified, this schema is based on the DataCite Metadata Schema (https://schema.datacite.org/)
type: object
properties:
  creators:
    type: array
    items:
      $ref: '#/components/schemas/Creator'
    minItems: 1
  titles:
    type: array
    items:
      $ref: '#/components/schemas/Title'
    minItems: 1
  publisher:
    $ref: '#/components/schemas/Publisher'
  publication_year:
    type: string
    pattern: '^[1-2][0-9]{3}$'
  subjects:
    type: array
    items:
      $ref: '#/components/schemas/Subject'
  contributors:
    type: array
    items:
      $ref: '#/components/schemas/Contributor'
    minItems: 1
  descriptions:
    type: array
    items:
      $ref: '#/components/schemas/Description'
    minItems: 1
  dates:
    type: array
    items:
      $ref: '#/components/schemas/Date'
    minItems: 1
  language:
    type: string
    pattern: '^[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*$'
  # Yes, this is plural in the DataCite schema.
  types:
    $ref: '#/components/schemas/ResourceType'
  version:
    type: string
  identifiers:
    type: array
    items:
      $ref: '#/components/schemas/Identifier'
    minItems: 1
required:
  - titles
  - creators
  - publication_year
  - types
  - identifiers
additionalProperties: false
components:
  schemas:
    Contributor:
      allOf:
        - $ref: '#/components/schemas/PersonOrOrganization'
        - type: object
          properties:
            contributor_type:
              type: string
              enum:
                - ContactPerson
                - DataCollector
                - DataCurator
                - DataManager
                - Distributor
                - Editor
                - HostingInstitution
                - Producer
                - ProjectLeader
                - ProjectManager
                - ProjectMember
                - RegistrationAgency
                - RegistrationAuthority
                - RelatedPerson
                - Researcher
                - ResearchGroup
                - RightsHolder
                - Sponsor
                - Supervisor
                - Translator
                - WorkPackageLeader
                - Other
      unevaluatedProperties: false
    Creator:
      allOf:
        - $ref: '#/components/schemas/PersonOrOrganization'
      unevaluatedProperties: false
    Date:
      type: object
      properties:
        date:
          type: string
          anyOf:
            - format: date-time
            - format: date
            - pattern: '^[1-2][0-9]{3}(-[0-1][1-9](-[0-3][1-9])?)?/[1-2][0-9]{3}(-[0-1][1-9](-[0-3][1-9])?)?$'
        date_type:
          type: string
          enum:
            - Accepted
            - Available
            - Copyrighted
            - Collected
            - Coverage
            - Created
            - Issued
            - Submitted
            - Updated
            - Valid
            - Withdrawn
            - Other
      required:
        - date
        # date_type is required in Datacite, but optional here.
      additionalProperties: false
    Description:
      type: object
      properties:
        description:
          type: string
        description_type:
          type: string
          enum:
            - Abstract
            - Methods
            - SeriesInformation
            - TableOfContents
            - TechnicalInfo
            - Other
      required:
        - description
        # description_type is required in Datacite, but optional here.
      additionalProperties: false
    PersonOrOrganization:
      type: object
      properties:
        name:
          type: string
        name_type:
          type: string
          enum:
            - Personal
            - Organizational
        given_name:
          type: string
        family_name:
          type: string
        name_identifiers:
          type: array
          items:
            type: object
            properties:
              name_identifier:
                type: string
              name_identifier_scheme:
                type: string
                enum:
                  # These are the examples schemes from DataCite. Additional schemes may be added.
                  - ORCID
                  - ISNI
                  - ROR
              required:
                - name_identifier
                - name_identifier_scheme
          minItems: 1
        # Yes, this is singular in the DataCite schema.
        affiliation:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              affiliation_identifier:
                type: string
              affiliation_identifier_scheme:
                type: string
                enum:
                  # These are the examples schemes from DataCite. Additional schemes may be added.
                  - ISNI
                  - ROR
            anyOf:
              required:
                - name
              required:
                - affiliation_identifier
            dependentRequired:
              affiliation_identifier:
                - affiliation_identifier_scheme
          minItems: 1
      required:
        - name
        # creator_type is required in Datacite, but optional here.
    Publisher:
      type: object
      properties:
        name:
          type: string
        publisher_identifier:
          type: string
        publisher_identifier_scheme:
          type: string
          enum:
            # These are the examples schemes from DataCite. Additional schemes may be added.
            - ROR
            - re3data
            - VIAF
            - Wikidata
            - Crossref Funder ID
            - ISNI
            - OpenDOAR
            - FAIRsharing
            - ISSN
      anyOf:
        required:
          - name
        required:
          - publisher_identifier
      dependentRequired:
        publisher_identifier:
          - publisher_identifier_scheme
    ResourceType:
      type: object
      properties:
        resource_type:
          type: string
        resource_type_general:
          type: string
          enum:
            - Audiovisual
            - Award
            - Book
            - BookChapter
            - Collection
            - ComputationalNotebook
            - ConferencePaper
            - ConferenceProceeding
            - DataPaper
            - Dataset
            - Dissertation
            - Event
            - Image
            - InteractiveResource
            - Instrument
            - Journal
            - JournalArticle
            - Model
            - OutputManagementPlan
            - PeerReview
            - PhysicalObject
            - Preprint
            - Project
            - Report
            - Service
            - Software
            - Sound
            - Standard
            - StudyRegistration
            - Text
            - Workflow
            - Other
      required:
        - resource_type_general
        - resource_type
      additionalProperties: false
    Subject:
      type: object
      properties:
        subject:
          type: string
        subject_scheme:
          type: string
        value_uri:
          type: string
          format: uri
      required:
        - subject
      additionalProperties: false
    Title:
      type: object
      properties:
        title:
          type: string
        title_type:
          type: string
          enum:
            - AlternativeTitle
            - Subtitle
            - TranslatedTitle
            - Other
      required:
        - title
      additionalProperties: false
    Identifier:
      type: object
      properties:
        identifier:
          type: string
        identifier_type:
          type: string
          enum:
            - DOI
            - RedivisReference
            - SearchWorksReference
      required:
        - identifier
        - identifier_type
      additionalProperties: false
