# Wait between retrieving each dataset
extract_sleep: 0.5
# Without authentication, Dryad allows 30 requests per minute
dryad_extract_sleep: 2.5

solr:
  url: http://localhost:8983/solr/dataworks

redivis:
  api_token: ~

zenodo:
  api_token: ~
